export const AUTH ='AUTH';
export const AUTH_FAILURE ='AUTH_FAILURE';
export const AUTH_SUCCESS='AUTH_SUCCESS';

export const GET_BUDGET ='GET_BUDGET';
export const GET_BUDGET_SUCCESS ='GET_BUDGET_SUCCESS';
export const GET_BUDGET_FAILURE='GET_BUDGET_FAILURE';